/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

buildscript {
    repositories {
        maven {url = uri("https://jitpack.io")}
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath("com.github.rcw3bb:gradle-modules-plugin:fit-gradle9-SNAPSHOT")
        classpath("com.palantir.baseline:gradle-baseline-java:6.66.0") // ofc palantir would have version 666
        classpath("com.palantir.javaformat:gradle-palantir-java-format:2.81.0")
        classpath("gradle.plugin.org.inferred:gradle-processors:2.1.0")
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.javamodularity.moduleplugin") version "1.8.15"
    id("com.diffplug.spotless") version "8.0.0"
    jacoco
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(25))
	}
}

javafx {
    version= "25"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.web")
    configurations = arrayOf("implementation");
}
configurations.all {
    resolutionStrategy {
        force("org.hamcrest:hamcrest-core:1.3")
    }
    exclude(group = "org.hamcrest", module = "hamcrest-core")
}

dependencies {
    implementation("org.mobicents.external.freetts:freetts:1.0")
    implementation("org.mobicents.external.freetts:en_us:1.0")
    implementation("org.mobicents.external.freetts:cmu_us_kal:1.0")
    implementation("org.mobicents.external.freetts:cmulex:1.0")
    implementation("org.mobicents.external.freetts:cmudict04:1.0")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:6.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:6.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:6.0.0")
    testImplementation("org.junit.platform:junit-platform-launcher:6.0.0")
    testImplementation("org.junit.platform:junit-platform-commons:6.0.0")
}

group = "org.virtuoso"
version = "0.1.0"
description = "escape"
java.sourceCompatibility = JavaVersion.VERSION_25
java.modularity.inferModulePath.set(false)

application {
    mainModule = "org.virtuoso.escape"
    mainClass = "org.virtuoso.escape.gui.App"
}

tasks.register<JavaExec>("tui") {
    group="application"
    description = "Run TerminalDriver"
    classpath=sourceSets.main.get().runtimeClasspath
    mainClass.set("org.virtuoso.escape.terminal.TerminalDriver")
    standardInput = System.`in`
}

tasks.register("format") {
    dependsOn("spotlessApply")
    description = "Formats code with the Palantir linter"
    group = "formatting"
}

tasks.withType<JavaCompile>() {
    options.compilerArgs.add("--enable-preview")
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
tasks.named<Test>("test") {
    jvmArgs("--enable-preview")
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}
tasks.withType<JavaExec>().configureEach {
    jvmArgs("--enable-preview")
}

spotless {
    isEnforceCheck=false
    java {
        palantirJavaFormat().formatJavadoc(true)
    }
}