import org.gradle.kotlin.dsl.kotlin

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

buildscript {
  repositories {
    maven { url = uri("https://jitpack.io") }
    mavenCentral()
    gradlePluginPortal()
  }
  dependencies {
    classpath("com.github.rcw3bb:gradle-modules-plugin:fit-gradle9-SNAPSHOT")
    classpath(
        "com.palantir.baseline:gradle-baseline-java:6.66.0"
    ) // ofc palantir would have version 666
    classpath("com.palantir.javaformat:gradle-palantir-java-format:2.81.0")
    classpath("gradle.plugin.org.inferred:gradle-processors:2.1.0")
  }
}

repositories {
  mavenLocal()
  mavenCentral()
  maven { url = uri("https://repo.maven.apache.org/maven2/") }
}

plugins {
  id("com.diffplug.spotless") version "8.0.0"
  jacoco
  kotlin("multiplatform") version "2.2.21"
  kotlin("plugin.serialization") version "2.2.21"
}

kotlin {
  js(IR) {
    browser()
    binaries.executable()
    outputModuleName = "virtuoso-escape"
  }
  jvm()
  sourceSets {
    jsMain {
      dependencies {
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.10.2")
        implementation("org.jetbrains.kotlinx:kotlinx-html-js:0.8.0")
      }
    }
    commonMain {
      dependencies { implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0") }
    }
    commonTest { dependencies { implementation(kotlin("test")) } }
  }
}

configurations.all {
  resolutionStrategy { force("org.hamcrest:hamcrest-core:1.3") }
  exclude(group = "org.hamcrest", module = "hamcrest-core")
}

group = "org.virtuoso"

version = "0.1.0"

description = "escape"

tasks.register<JavaExec>("tui") {
  group = "application"
  description = "Run TerminalDriver"
  classpath =
      kotlin.jvm().compilations.getByName("main").let {
        it.runtimeDependencyFiles + it.output.allOutputs
      }
  mainClass.set("org.virtuoso.escape.terminal.TerminalDriver")
  standardInput = System.`in`
}

tasks.register("format") {
  dependsOn("spotlessApply")
  description = "Formats code with the Palantir linter"
  group = "formatting"
}

tasks.register("coverage") {
  dependsOn("jacocoTestReport")
  description = "Generates a test coverage report in build/reports/jacoco"
  group = "test"
}

tasks.register("formatCheck") {
  dependsOn("spotlessCheck")
  description = "Checks if codebase is formatted correctly."
  group = "formatting"
}

tasks.named<Test>("jvmTest") {
  jvmArgs("--enable-preview")
  useJUnitPlatform()
  testLogging {
    events("passed", "skipped", "failed")
    exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    showStandardStreams = true
  }
}

tasks.withType<JavaExec>().configureEach {
  jvmArgs("--enable-preview")
  standardInput = System.`in`
}

spotless {
  isEnforceCheck = false
  kotlin {
    ktfmt()
    target("src/**/*.kt")
    toggleOffOn("@formatter:off", "@formatter:on")
  }
  kotlinGradle { ktfmt() }
  javascript {
    target("src/**/*.js")
    prettier().npmInstallCache().config(mapOf("tabWidth" to 4))
  }
}

tasks.withType<JavaCompile>().configureEach { options.release.set(24) }
