/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    `application`
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.javamodularity.moduleplugin") version "1.8.12"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

javafx {
    modules = listOf("javafx.controls", "javafx.fxml")
    configurations = arrayOf("implementation");
}
configurations.all {
    resolutionStrategy {
        force("org.hamcrest:hamcrest-core:1.3")
    }
    exclude(group = "org.hamcrest", module = "hamcrest-core")
}

dependencies {
    implementation("org.mobicents.external.freetts:freetts:1.0")
    implementation("org.mobicents.external.freetts:en_us:1.0")
    implementation("org.mobicents.external.freetts:cmu_us_kal:1.0")
    implementation("org.mobicents.external.freetts:cmulex:1.0")
    implementation("org.mobicents.external.freetts:cmudict04:1.0")
    implementation("com.googlecode.json-simple:json-simple:1.1.1")
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
}

group = "org.virtuoso"
version = "0.1.0"
description = "escape"
java.sourceCompatibility = JavaVersion.VERSION_25
java.modularity.inferModulePath.set(false)

application {
    mainModule = "org.virtuoso.escape"
    mainClass = "org.virtuoso.escape.gui.HelloApplication"
}

tasks.register<JavaExec>("tui") {
    group="application"
    description = "Run TerminalDriver"
    classpath=sourceSets.main.get().runtimeClasspath
    mainClass.set("org.virtuoso.escape.terminal.TerminalDriver")
    standardInput = System.`in`
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
