/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "virtuoso-escape"

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = uri("https://jitpack.io")}
    }
}